replicaCount: 2

image:
  repository: 055029294053.dkr.ecr.ap-south-1.amazonaws.com/mdapkr-fastapi
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  port: 80

containerPort: 8000

mongodb:
  uri: "mongodb://mongo:27017"
