apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
type: Opaque
data:
  username: bW9uZ29hZG1pbg==     # base64 for 'mongoadmin'
  password: c2VjcmV0UGFzc3dvcmQ= # base64 for 'secretPassword'
