apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "mdapkr.fullname" . }}
  labels:
    app: {{ include "mdapkr.name" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "mdapkr.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "mdapkr.name" . }}
    spec:
      containers:
        - name: {{ include "mdapkr.name" . }}
          image: "{{ .Values.fastapi.image.repository }}:{{ .Values.fastapi.image.tag }}"
          imagePullPolicy: {{ .Values.fastapi.image.pullPolicy }}
          ports:
            - containerPort: 8000
          env:
            - name: MONGO_URL
              value: "mongodb://mongo:27017"
            - name: MONGO_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: username
            - name: MONGO_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: password
          resources:
            requests:
              cpu: 100m
            limits:
              cpu: 500m
