name: CD Deploy

on:
  repository_dispatch:
    types: [deploy-mdapkr]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials using OIDC
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: arn:aws:iam::055029294053:role/GitHubActionsECRPush
          aws-region: ap-south-1

      - name: Update kubeconfig for EKS cluster
        run: |
          aws eks update-kubeconfig --region ap-south-1 --name mdapkr-cluster

      - name: Set up kubectl
        uses: azure/setup-kubectl@v3

      - name: Deploy using Helm
        run: |
          helm dependency update ./helm/mdapkr/mdapkr
          helm upgrade --install mdapkr ./helm/mdapkr/mdapkr \
            --set fastapi.image.repository=055029294053.dkr.ecr.ap-south-1.amazonaws.com/mdapkr-fastapi \
            --set fastapi.image.tag=${{ github.event.client_payload.image_tag }}
