name: CD Deploy from App Repo

on:
  repository_dispatch:
    types: [trigger-deploy]

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::055029294053:role/GitHubActionsECRPush
          aws-region: ap-south-1

      - name: Update kubeconfig
        run: |
          aws eks update-kubeconfig --region ap-south-1 --name mdapkr-cluster

      - name: Helm deploy
        env:
          IMAGE_TAG: ${{ github.event.client_payload.image_tag }}
          ECR_REGISTRY: 055029294053.dkr.ecr.ap-south-1.amazonaws.com
        run: |
          helm dependency update ./helm/mdapkr/mdapkr
          helm upgrade --install mdapkr ./helm/mdapkr/mdapkr \
            --set fastapi.image.repository=$ECR_REGISTRY/mdapkr-fastapi \
            --set fastapi.image.tag=$IMAGE_TAG
